void alg3(){
  ledsclear();
  CRGB cvet1 = CHSV( random(50, 255),random(50, 255),random(50, 255));
  leds[3] = cvet1;
  leds[10] = cvet1;
  leds[17] = cvet1;
  leds[24] = cvet1;
  FastLED.show();
  delay(wait);
  leds[3] = CRGB::Black;
  leds[10] = CRGB::Black;
  leds[17] = CRGB::Black;
  leds[6] = cvet1;
  leds[12] = cvet1;
  leds[18] = cvet1;
  FastLED.show();
  delay(wait);
  leds[6] = CRGB::Black;
  leds[12] = CRGB::Black;
  leds[18] = CRGB::Black;
  leds[25] = cvet1;
  leds[26] = cvet1;
  leds[27] = cvet1;
  FastLED.show();
  delay(wait);
  leds[25] = CRGB::Black;
  leds[26] = CRGB::Black;
  leds[27] = CRGB::Black;
  leds[32] = cvet1;
  leds[40] = cvet1;
  leds[48] = cvet1;
  FastLED.show();
  delay(wait);
  leds[32] = CRGB::Black;
  leds[40] = CRGB::Black;
  leds[48] = CRGB::Black;
  leds[31] = cvet1;
  leds[38] = cvet1;
  leds[45] = cvet1;
  FastLED.show();
  delay(wait);
  leds[31] = CRGB::Black;
  leds[38] = CRGB::Black;
  leds[45] = CRGB::Black;
  leds[30] = cvet1;
  leds[36] = cvet1;
  leds[42] = cvet1;
  FastLED.show();
  delay(wait);
  leds[30] = CRGB::Black;
  leds[36] = CRGB::Black;
  leds[42] = CRGB::Black;
  leds[23] = cvet1;
  leds[22] = cvet1;
  leds[21] = cvet1;
  FastLED.show();
  delay(wait);
  leds[23] = CRGB::Black;
  leds[22] = CRGB::Black;
  leds[21] = CRGB::Black;
  leds[0] = cvet1;
  leds[8] = cvet1;
  leds[16] = cvet1;
  FastLED.show();
  delay(wait);

  ledsclear();
  cvet1 = CHSV( random(50, 255),random(50, 255),random(50, 255));
  leds[3] = cvet1;
  leds[10] = cvet1;
  leds[17] = cvet1;
  leds[24] = cvet1;
  FastLED.show();
  delay(wait);
  leds[3] = CRGB::Black;
  leds[10] = CRGB::Black;
  leds[17] = CRGB::Black;
  leds[6] = cvet1;
  leds[12] = cvet1;
  leds[18] = cvet1;
  FastLED.show();
  delay(wait);
  leds[6] = CRGB::Black;
  leds[12] = CRGB::Black;
  leds[18] = CRGB::Black;
  leds[25] = cvet1;
  leds[26] = cvet1;
  leds[27] = cvet1;
  FastLED.show();
  delay(wait);
  leds[25] = CRGB::Black;
  leds[26] = CRGB::Black;
  leds[27] = CRGB::Black;
  leds[32] = cvet1;
  leds[40] = cvet1;
  leds[48] = cvet1;
  FastLED.show();
  delay(wait);
  leds[32] = CRGB::Black;
  leds[40] = CRGB::Black;
  leds[48] = CRGB::Black;
  leds[31] = cvet1;
  leds[38] = cvet1;
  leds[45] = cvet1;
  FastLED.show();
  delay(wait);
  leds[31] = CRGB::Black;
  leds[38] = CRGB::Black;
  leds[45] = CRGB::Black;
  leds[30] = cvet1;
  leds[36] = cvet1;
  leds[42] = cvet1;
  FastLED.show();
  delay(wait);
  leds[30] = CRGB::Black;
  leds[36] = CRGB::Black;
  leds[42] = CRGB::Black;
  leds[23] = cvet1;
  leds[22] = cvet1;
  leds[21] = cvet1;
  FastLED.show();
  delay(wait);
  leds[23] = CRGB::Black;
  leds[22] = CRGB::Black;
  leds[21] = CRGB::Black;
  leds[0] = cvet1;
  leds[8] = cvet1;
  leds[16] = cvet1;
  FastLED.show();
  delay(wait);
}
